#!/usr/bin/bash

# write your code here

re_str='[a-z]+_to_[a-z]+'
re_num='^[+-]?[0-9]+([.][0-9]+)?$'
file_name="definitions.txt"
touch $file_name

function add_def {
    echo "Enter a definition:"
    read -a user_input
    arr="${#user_input[@]}"
    str="${user_input[0]}"
    num="${user_input[1]}"


    if [[ "$str" =~ $re_str ]] && [[ "$arr" -eq 2 ]] && [[ "$num" =~ $re_num ]]; then
#      echo "Enter a value to convert:"
#      read value
#      while [[ ! "$value" =~ $re_num ]]
#      do
#        echo "Enter a float or integer value!"
#        read value_f
#        value=$value_f
#      done
#      echo "Result: $(bc -l <<<$num*$value)"
        num_lines=$(wc -l < definitions.txt)
        add_sn=$((num_lines + 1))
        prefix="$add_sn".
        line="${user_input[*]}"
        echo "$prefix" "$line" >> "$file_name"
    else
      echo "The definition is incorrect!"
      add_def
    fi
}

function del_def {
    if [ -s definitions.txt ]; then
        echo "Type the line number to delete or '0' to return"
        cat $file_name
        num_lines=$(wc -l < definitions.txt)
        read line_del_num
        while [ $line_del_num -gt $num_lines ] || [ -z $line_del_num ] || [[ "$line_del_num" == "" ]]
        do
            echo "Enter a valid line number!"
            read num
            line_del_num=$num
        done
        if [ $line_del_num -eq 0 ]; then
            return
        else
            sed -i "${line_del_num}d" "$file_name"
        fi
    else
        echo "Please add a definition first!"
    fi
}

echo "Welcome to the Simple converter!"
echo ""
echo "Select an option"
echo "0. Type '0' or 'quit' to end program"
echo "1. Convert units"
echo "2. Add a definition"
echo "3. Delete a definition"
read menu_select

while true
do
  case $menu_select in
    0)
      echo "Goodbye!"
      exit
        ;;
    "quit")
      echo "Goodbye!"
      exit
        ;;
    1)
      echo "Not implemented!"
      echo ""
      echo "Select an option"
      echo "0. Type '0' or 'quit' to end program"
      echo "1. Convert units"
      echo "2. Add a definition"
      echo "3. Delete a definition"
      read num_in
      menu_select=$num_in
      ;;
    2)
      add_def
      echo ""
      echo "Select an option"
      echo "0. Type '0' or 'quit' to end program"
      echo "1. Convert units"
      echo "2. Add a definition"
      echo "3. Delete a definition"
      read num_in
      menu_select=$num_in
      ;;
    3)
      del_def
      echo ""
      echo "Select an option"
      echo "0. Type '0' or 'quit' to end program"
      echo "1. Convert units"
      echo "2. Add a definition"
      echo "3. Delete a definition"
      read num_in
      menu_select=$num_in
      ;;
    *)
      echo "Invalid option!"
      echo ""
      echo "Select an option"
      echo "0. Type '0' or 'quit' to end program"
      echo "1. Convert units"
      echo "2. Add a definition"
      echo "3. Delete a definition"
      read num_in
      menu_select=$num_in
      ;;
  esac
done


#echo "Enter a definition:"
#read -a user_input
#arr="${#user_input[@]}"
#str="${user_input[0]}"
#num="${user_input[1]}"

#if [[ "$str" =~ $re_str ]] && [[ "$arr" -eq 2 ]] && [[ "$num" =~ $re_num ]]; then
#  echo "Enter a value to convert:"
#  read value
#  while [[ ! "$value" =~ $re_num ]]
#  do
#    echo "Enter a float or integer value!"
#    read value_f
#    value=$value_f
#  done
#  echo "Result: $(bc -l <<<$num*$value)"
#else
#  echo "The definition is incorrect!"
#fi